### ISSUE TITLE
Being able to customize MEDIA_URL

### ISSUE THREAD

**Issue by davemerwin** [sunlightlabs/django-mediasync#10]
Would it be possible to use directories other than what is at MEDIA_URL? Maybe the settings default MEDIA_URL but they could be customized.

**Comment by jcarbaugh** [comment]
I'm not sure I understand what you are trying to do here. Could you give an example? Thanks!

**Comment by davemerwin** [comment]
Would it be posible to say do the following:

Setup a Static URL .
Then point MEDIASYNC_URL to the static directory instead of the default MEDIA_URL

Like this:

# Absolute path to the directory that holds static files like app media.

# Example: "/home/media/media.lawrence.com/apps/"

STATIC_ROOT = os.path.join(PROJECT_ROOT, '..', 'site_media', 'static')

# URL that handles the static files like app media.

# Example: "http://media.lawrence.com"

STATIC_URL = '/static_url/'

# Mediasync media url redirect

MEDIASYNC_ROOT = STATIC_ROOT
MEDIASYNC_URL = STATIC_URL

Thoughts?

**Comment by jcarbaugh** [comment]
I've implemented this in master. I'll tag it and create a new 2.0 release once I get one more feature finished.
