### ISSUE TITLE
Failure to sync modified media

### ISSUE THREAD

**Issue by gtaylor** [sunlightlabs/django-mediasync#14]
Looks like ./manage.py syncmedia sometimes fails to sync modified stuff with S3. I Change a few JavaScript files and they haven't been getting synced up.

Any way to fix/force this?

**Comment by jcarbaugh** [comment]
The syncing works by comparing a hash between the local file and the hash of the file stored on S3. What are the specifics of the changes that were made to the local files? Is there a way you could post the local and remote versions of the files that were not syncing? I'd like to try it out to see what is causing the hash comparison to fail or find out if it is something different.

There is a _force_ argument to the Backend.put method the will upload all files regardless of the hash comparison. As is there is no way to specify force from the management command. I'll add that.

**Comment by jcarbaugh** [comment]
Okay, just pushed the --force option on the syncmedia management command.

**Comment by gtaylor** [comment]
Thanks. I'll keep an eye out to see if I can catch this when it happens again.

**Comment by gtaylor** [comment]
I haven't been able to reproduce this since the syncing modifications I made with hidden directories. Not at all sure how it would be related to this, probably isn't. Closing this until/if this happens again.
