### ISSUE TITLE
SSL Media?

### ISSUE THREAD

**Issue by gtaylor** [sunlightlabs/django-mediasync#16]
From what I can tell, there isn't any mechanism in to handle media over SSL. I'm not sure if this is something that can be worked into the way things are right now without some awful hacks. Can we do anything to make this easier?

Just as an example of what I'm talking about, we've got a site that's about 60%/30% HTTP to HTTPS. On the SSL pages, the media also must be coming through SSL, or a lot of browsers complain. This is the big problem we're trying to figure out. Any pointers would be great.

**Comment by gtaylor** [comment]
I've started to work on a fix for this in my fork. I think I've got a way to do this reasonably cleanly. Stay tuned, kids.

**Comment by jcarbaugh** [comment]
And thank you again for this patch. Currently in master.
