### ISSUE TITLE
Add support for new features in Django 1.3

### ISSUE THREAD

**Issue by jezdez** [sunlightlabs/django-mediasync#23]
The upcoming Django 1.3 provides a few new settings that are supposed to be used for non-user generated files (STATIC_URL and STATIC_ROOT) and will be used by Django's media framework (forms, admin etc). I think it'd be useful to adopt those for mediasync, too.

**Comment by jcarbaugh** [comment]
If I read the 1.3 docs correctly, the only change needed by mediasync would be to first check for STATIC_\* settings and then fallback to MEDIA_\* if static does not exists. Sound about right?

**Comment by jcarbaugh** [comment]
Just committed Rob's changes for this. Thanks!

**Comment by jezdez** [comment]
w00t!
