### ISSUE TITLE
Assert Error on AWS_BUCKET is killing TEMPLATE_DEBUG

### ISSUE THREAD

**Issue by davemerwin** [sunlightlabs/django-mediasync#24]
I've isolated it to this one setting. If I turn it off, the TEMPLATE_DEBUG works properly and shows me the "fancy traceback". As soon as I turn it back on, the TEMPLATE_DEBUG stops working and the traceback renders without any styling. Any ideas on what could be causing this?

**Comment by jcarbaugh** [comment]
What exactly do you mean by turn it off? Remove it from the MEDIASYNC settings dict? There is an assert that is done when the s3 client is initialized, but that can probably be removed without causing any problems. Could you send a copy of your MEDIASYNC settings? Not having AWS_BUCKET set would cause that assert to fail so I'm not sure why it worked when you removed that settings.

**Comment by davemerwin** [comment]
I thought about that after I wrote it and realized that it may not have been clear. Of course the assert error happens when I remove the bucket name. What I mean is... the AWS_BUCKET seems to cause the TEMPLATE_DEBUG to not work.

If I purposefully introduce a template syntax error, and the AWS_BUCKET is active, than the TEMPLATE_DEBUG doesn't work. I get a traceback, but it's the raw text file. However, if I comment out the AWS_BUCKET setting, the TEMPLATE_DEBUG works again.

Does that make more sense?

**Comment by jcarbaugh** [comment]
Sorry that I haven't had more time to look into this. I haven't been able to reproduce this locally, so I still may not be understanding the problem. If it's not too much trouble, could you write an explicit list of steps to trigger the problem?

**Comment by jcarbaugh** [comment]
Are you still having this issue? I'm going to close this, but feel free to reopen if you are still having the problem.
