### ISSUE TITLE
CSS Composition and relative references

### ISSUE THREAD

**Issue by ubiquitousthey** [sunlightlabs/django-mediasync#28]
I am using several js plugins that have their own CSS files.  Each plugin is composed slightly differently.  When I use the composition feature on the CSS files they lose their links to relative files.  I understand what it is doing, but I am not sure of a good solution.  Right now I am rearranging everything.  It would be great if the composer would parse the CSS file and either modify the files sent to the CDN or move the files around, etc so that the CSS files would work unmodified.  Any ideas?

**Comment by gtaylor** [comment]
That is a pretty difficult issue. We've just had to change the paths, too. Perhaps another tool/app has solved this problem already and can be used as a reference?

**Comment by ubiquitousthey** [comment]
Thanks for the response.  It seems to me the best option would be a preprocessor that parses CSS and rewrites paths to external references so that the files can stay where they are.  Perhaps I'll get space for this in the next few months.  It would only have to look for a small subset of CSS, so it might not be too difficult.  Before (and if) I start, I'll look around for some ideas.  Thanks for your work.
