### ISSUE TITLE
Zero bytes joined file uploaded to S3

### ISSUE THREAD

**Issue by akramic** [sunlightlabs/django-mediasync#29]
Hello, I'm sure I'm doing something silly. 
I am setting debug to false and running syncmedia. My joined js and css files seem to be created and uploaded to my S3 bucket but the files are 0 bytes in length!

Debug true seems to work fine.

I have a feeling this has something to do with my confusion with media files and static files. My understanding is that the former are for user uploaded files with the latter being for static site files. As I am using boto to directly upload user files the media url and media root are empty strings in my settings.py file.

Any suggestions would be gratefully received.

**Comment by jcarbaugh** [comment]
Hello there! Are you running from master or a specific release?

**Comment by jcarbaugh** [comment]
Are you still having this problem? I'm going to close this ticket, but feel free to reopen if you are still having the issue.

**Comment by mnazim** [comment]
I am have exact same problem with v2.2.0. But seems like I do not have permission to reopen this issue.

**Comment by jcarbaugh** [comment]
Do the unjoined files sync correctly? Would you be able to pass along your MEDIASYNC settings and the JS files that are not joining correctly?

**Comment by mnazim** [comment]
I deeply apologize for the false alarm. We were sifting through our JS files line by line, over and over whole day and just found a typo 5 min ago. Fixing the typo fixed the issue. 

I once again apologize for false alarm.

PS. It would great though if some kind of warning etc. can be shown on the console.

**Comment by jcarbaugh** [comment]
That's good to hear! I've actually had this happen before as well. It is due to the JS minification that is done by default. I've come to realize that this can lead to a lot of problems so I've considered turning minification off by default. Clearer error reporting would be good too!
