### ISSUE TITLE
mediasync outputs only XHTML

### ISSUE THREAD

**Issue by robhudson** [sunlightlabs/django-mediasync#3]
For projects that use an HTML4 doctype, the output from mediasync produces invalid HTML.  Specifically the `<link>` tag.

I don't know the best way to solve this?  Yet another setting?

**Comment by jcarbaugh** [comment]
I think a setting is the only way to solve it. Sadly a closing tag on link would be invalid in XHTML. MEDIASYNC_XHTML_SYNTAX = True/False, True by default. Any objections to that?

**Comment by robhudson** [comment]
Or MEDIASYNC_DOCTYPE = 'xhtml1'/'html4'?  Is HTML5's link tag any different?

**Comment by jcarbaugh** [comment]
HTML5 will validate with either the XHTML self-closed tag or an implicitly closed tag. Should the options then be:

html4
    <link></link>

html5
    <link>

xhtml
    <link />

**Comment by robhudson** [comment]
Looks pretty good to me.

**Comment by jcarbaugh** [comment]
add MEDIASYNC_DOCTYPE setting to change the output of template tags for HTML4, HTML5, and XHTML. Closed by 815bc4fb0298a05d10f3dcb200263d8f971c6b83
