### ISSUE TITLE
Support for loading variables with media_url

### ISSUE THREAD

**Issue by ericbuckley** [sunlightlabs/django-mediasync#30]
The `media_url` template tag only supports rendering urls for string arguments, it would be convient if you could also pass it a variable and the template tag was intelligent enough to evaluate first.  For example:

```
<img src="{% media_url object.avatar.url %}" />
```

**Comment by jcarbaugh** [comment]
This should be working now! Template tags are one of the big areas that are missing tests. I hope to work on that tomorrow to get them covered. Until then, this worked on a test project.

**Comment by ericbuckley** [comment]
Impressive 4 hour turnaround, much appreciated.  Thanks for the good work!

**Comment by jcarbaugh** [comment]
You caught me at a good time while I was working on other stuff. Features that have been waiting for months are jealous :)

**Comment by ericbuckley** [comment]
I'm not sure this implementation works in all cases.  From what I understand with templatetags, to be efficient they are only constructed once per unique argument set, then rendered multiple times as needed.  So in the case where you have a list of objects and create a template like so:

```
{% for o in objects %}
    <img src="{% media_url o.avatar.url %}
{% endfor %}
```

Even though all of the avatars may differ, the code is only generating a `MediaUrlTagNode` once, thus after the first render, `self.path` is modified to an actual url so all subsequent renders result in returning the firsts url.

On a side note, I believe the current implementation violates some [thread-safety concerns](http://docs.djangoproject.com/en/1.3/howto/custom-template-tags/#thread-safety-considerations)

**Comment by jcarbaugh** [comment]
Ah thanks for noticing that. I was only evaluating the variable once, instead of per render call. That's been fixed and I added a test case for it.
