### ISSUE TITLE
0kb in all.css and all.js

### ISSUE THREAD

**Issue by davemerwin** [sunlightlabs/django-mediasync#40]
Everything works locally. When I run syncmedia, it creates an all.css file and an all.js file in the correct directories.

But there is nothing in the files. I've removed all teh .js files and then I've removed all the content of the screen.css files, but nothing changes it.

Here are my settings:

```
MEDIA_VERSION = '0005'  # increment to bust cache
MEDIASYNC = {
    'AWS_KEY': "XXXXXXXXXXXXXXX",
    'AWS_SECRET': "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    'AWS_BUCKET': 'MYBUCKETNAME',
    'AWS_PREFIX': '%s' % MEDIA_VERSION,
    'BACKEND': 'mediasync.backends.s3',
    'DOCTYPE': 'html5',
    'AWS_GZIP': True,
    'PROCESSORS': ('mediasync.processors.yuicompressor.css_minifier',
               'mediasync.processors.yuicompressor.js_minifier'),
    'YUI_COMPRESSOR_PATH': '~/bin/yuicompressor.jar',
    'JOINED': {
        'css/all.css': (
            'css/screen.css',),
        'js/all.js': (
            'js/jquery.1.7.1.js',
            'js/jquery.fitvids.js',
            'js/jquery.tipsy.js',
            'js/app.js',
        ),
    },
}
```

**Comment by davemerwin** [comment]
MYBUCKETNAME is obviously the name of my bucket

**Comment by davemerwin** [comment]
Also, the sub files aren't being written in at all - for instance, screen.css is no where to be found.

**Comment by davemerwin** [comment]
Even some suggestions on how to trouble shoot. I'm not seeing any error outputs.

**Comment by gtaylor** [comment]
Your path to YUI Compressor needs to be absolute.

**Comment by davemerwin** [comment]
Actually, it works fine with a relative path. In fact, I have it running that way with several projects. But, even if I pull it out... still nothing in the all.css or all.js.

**Comment by davemerwin** [comment]
Sorry, not relative, but home. "~" = $HOME

**Comment by gtaylor** [comment]
Try an absolute path to the processor.

**Comment by davemerwin** [comment]
Nope, absolute path makes no difference. Still no data in the all.js or all.css.

**Comment by davemerwin** [comment]
Does anyone have a suggestion on how to troubleshoot?

**Comment by davemerwin** [comment]
it was an absolute path to my static dir
