### ISSUE TITLE
Deprecating conditional template tag support

### ISSUE THREAD

**Issue by jcarbaugh** [sunlightlabs/django-mediasync#5]
I'm considering deprecating the following template tags: css_ie, css_ie6, css_ie7, ie, ie6, ie7. mediasync is meant to manage media pushes to production and proper linking to the media. The conditional support is really outside the scope of what mediasync is meant to do. The conditionals are also fairly simple and shouldn't be something that you need a template tag to do.

Does anyone rely on these tags or object to them being deprecated and eventually removed?

**Comment by robhudson** [comment]
The alternative is simply:

```
<!--[if IE]>{% css "myfile.css" %}<![endif]-->
```

Right?

If so, that makes a lot of sense to deprecate them.

**Comment by jcarbaugh** [comment]
Yep, that would be the alternative.

**Comment by jcarbaugh** [comment]
add deprecation warnings to IE conditional template tags. will be removed before 1.0 release. Closed by 2e37b54530553261cd762b63aa902d536e46006c.
