### ISSUE TITLE
Pip install possibility

### ISSUE THREAD

**Issue by DenisMir** [sunlightlabs/django-mediasync#7]
It would be awesome if you could add a possibility to install django-mediasync with "pip".

**Comment by DenisMir** [comment]
It is already working. Close.

**Comment by jcarbaugh** [comment]
Yep, `pip install django-mediasync` works. Thanks!

**Comment by DenisMir** [comment]
Yeah. The first time it did not work. But now it is working just fine. Thank you for releasing this app. :)
