### ISSUE TITLE
JS doesn't always get "jsmin"d

### ISSUE THREAD

**Issue by ghost** [sunlightlabs/django-mediasync#8]
Reason is because not all mimetypes are listed to trigger the jsmin on line 41 of mediasync/clients/s3.py.  That should add "application/javascript" and "application/x-javascript".

**Comment by orcasgit** [comment]
Once media is uploaded and zipped, you can verify by unzipping with curl: `curl --compressed http://path/to/js`.  Not sure how much of an issues this is since it's zipped anyway, but to be complete, it should probably include all mimetypes.

**Comment by robhudson** [comment]
Must have made this comment from my work account... Anyway, I pushed a fix on my branch: http://github.com/robhudson/django-mediasync/

**Comment by jcarbaugh** [comment]
Much appreciated, Rob! I was thinking more about the pluggable processors (zip, cssmin, jsmin) a few days ago. A coworker wants to use SASS for their CSS and the processors seems like the way to go. I'll probably get started on that this weekend.
