### ISSUE TITLE
hidden directories

### ISSUE THREAD

**Issue by dmishe** [sunlightlabs/django-mediasync#9]
If i want to sync media that was checked out from svn it'll sync each .svn directory, which is bad.

**Comment by jcarbaugh** [comment]
I'm working on a refactoring this weekend that will support pluggable backends and file processors. I think this is something that can be fixed after that is done.

If I remember correctly, directories beginning with _ or . SHOULD be ignored in the syncing.

**Comment by gtaylor** [comment]
Looks like it might be ignoring the top level .svn directory, but grabbing the other directories and including any of their .svn sub-directories.

**Comment by gtaylor** [comment]
Just worked on a fix for this. You may find the diff at:

http://pastebin.com/5snz7Rev

Hope that helps.

**Comment by gtaylor** [comment]
This should be fixed in the latest master branch.
